# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eprimora' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Eprimora
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Blueprints'
  pod 'SharkORM'
  pod 'BetterSegmentedControl'
  pod 'ReachabilitySwift'
  pod 'McPicker'
end
